name: 'Testing release'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run TFLint
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
    - name: Get changed files
      id: create-release
      run: gh release create ${VERSION} -F changelog.md