name: Release test

on:
  pull_request:
    branches: [ main ]

jobs:
  create-release-with-changes-from-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Get information from last merged PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUM="2"
          echo "PR_NUM $PR_NUM"
          echo "PR_NUM=$PR_NUM" >> $GITHUB_ENV

      - name: Create release in Github
        id: create-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr view $PR_NUM --json body | jq -r .body > pr-changelog.md
          cat pr-changelog.md
          gh release create "v$(date +%Y.%m.%d-%H%M)" -F pr-changelog.md
          # Actions need to be set to have "Read and write permissions"
