name: secrets test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stv-io/tg-gcp-ci-tools-image/tg-gcp-ci-tools-image:v0.1.4
      options: --user root # https://github.com/actions/checkout/issues/1014
    steps:
      - uses: 'actions/checkout@v3'
      - name: test
        env:
          GIT_SSH_COMMAND: "ssh-keyscan github.com > known_hosts
            && chmod 600 known_hosts
            && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
        run: | 
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output ./id_rsa .github/keys/id_rsa.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output /home/tfuser/google_application_credentials .github/keys/application_default_credentials.json.gpg
          chmod 600 known_hosts id_rsa
          export GOOGLE_APPLICATION_CREDENTIALS=/home/tfuser/google_application_credentials
          file /home/tfuser/google_application_credentials
          file ./id_rsa